module.exports={
    USERS_COLLECTION:'users',
    ADMIN_COLLECTION:'admin',
    PRODUCTS_COLLECTION:'products',
    CATEGORY_COLLECTION:'category',
    CART_COLLECTION:'cart',
    ADDRESS_COLLECTION:'address',
    ORDER_COLLECTION:'order',
    HOMEPAGE_COLLECTION:'homepage'
}